github.com:
    users:
        HemmiGames:
            oauth_token: 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
    git_protocol: https
    user: HemmiGames
    oauth_token: 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
